"""Public filter exports for the noise-cleaning toolkit."""

from .distance_based import (
    AllKNN,
    DISTANCE_BASED_FILTERS,
    ENNFilter,
    ENNFilterResult,
    ENNProb,
    ENNProbFilter,
    ENNProbFilterResult,
    ENNTh,
    MultiEditFilter,
    MultiEditFilterResult,
    NCNEdit,
    NCNEditFilterResult,
    TomekLinks,
)
from .noiseScoreFiltering import NoiseScoreFilter
from .classifier_based import (
    CLASSIFIER_BASED_FILTERS,
    ClassificationFilter,
    ClassificationFilterResult,
    ClassificationFilterSHAPExplanation,
    ClassificationFilterSHAPReport,
    ShapDifferenceInstanceExplanation,
    ShapDifferenceReport,
    CVCFFilter,
    CVCFFilterResult,
    FEF,
    FilterEnsembleFilter,
    FilterEnsembleFilterResult,
    EnsembleFilterResult,
    EnsembleFiltering,
    INFFC_old_wrong,
    INFFC_old_wrongFilterResult,
    INFFC_old_wrongIterationInfo,
    IPFIterationInfo,
    IterativePartitioningFilter,
    IterativePartitioningFilterResult,
    compute_explanatory_noise_score,
    compute_shap_class_difference,
    explain_classification_filter_shap_difference,
    explain_classification_filter_noisy_instances,
    explain_instance_shap_difference,
    explain_noisy_instances_with_shap,
    TABPFNClassificationFilter,
    c45_like,
)


def print_available_filters():
    """Return the names of all built-in filter families."""
    return DISTANCE_BASED_FILTERS + CLASSIFIER_BASED_FILTERS


__all__ = [
    "AllKNN",
    "CLASSIFIER_BASED_FILTERS",
    "ClassificationFilter",
    "ClassificationFilterResult",
    "ClassificationFilterSHAPExplanation",
    "ClassificationFilterSHAPReport",
    "CVCFFilter",
    "CVCFFilterResult",
    "DISTANCE_BASED_FILTERS",
    "FEF",
    "ENNFilter",
    "ENNFilterResult",
    "ENNProb",
    "ENNProbFilter",
    "ENNProbFilterResult",
    "ENNTh",
    "EnsembleFilterResult",
    "EnsembleFiltering",
    "FilterEnsembleFilter",
    "FilterEnsembleFilterResult",
    "INFFC_old_wrong",
    "INFFC_old_wrongFilterResult",
    "INFFC_old_wrongIterationInfo",
    "IPFIterationInfo",
    "IterativePartitioningFilter",
    "IterativePartitioningFilterResult",
    "MultiEditFilter",
    "MultiEditFilterResult",
    "NCNEdit",
    "NCNEditFilterResult",
    "NoiseScoreFilter",
    "ShapDifferenceInstanceExplanation",
    "ShapDifferenceReport",
    "compute_explanatory_noise_score",
    "compute_shap_class_difference",
    "explain_classification_filter_noisy_instances",
    "explain_classification_filter_shap_difference",
    "explain_instance_shap_difference",
    "explain_noisy_instances_with_shap",
    "TABPFNClassificationFilter",
    "TomekLinks",
    "c45_like",
    "print_available_filters",
]
